### ISSUE TITLE
Deleting collection groups causes mass collection deletion

### ISSUE THREAD

**Issue by ryanmitchell** [getcandy/getcandy#292]
See attached video which helps explain it better.
https://www.loom.com/share/8141ad15e605449b9789fe61a7bc09f3

Full error trace as follows:

```
(PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails (`10ofthose_candy_hub`.`getcandy_collection_customer_group`, CONSTRAINT `getcandy_collection_customer_group_collection_id_foreign` FOREIGN KEY (`collection_id`) REFERENCES `getcandy_collections) at /home/ploi/10ofthose.servers.tc/vendor/laravel/framework/src/Illuminate/Database/Connection.php:526)
[stacktrace]
#0 /home/ploi/10ofthose.servers.tc/vendor/laravel/framework/src/Illuminate/Database/Connection.php(526): PDOStatement->execute()
#1 /home/ploi/10ofthose.servers.tc/vendor/laravel/framework/src/Illuminate/Database/Connection.php(705): Illuminate\\Database\\Connection->Illuminate\\Database\\{closure}()
#2 /home/ploi/10ofthose.servers.tc/vendor/laravel/framework/src/Illuminate/Database/Connection.php(672): Illuminate\\Database\\Connection->runQueryCallback()
#3 /home/ploi/10ofthose.servers.tc/vendor/laravel/framework/src/Illuminate/Database/Connection.php(533): Illuminate\\Database\\Connection->run()
#4 /home/ploi/10ofthose.servers.tc/vendor/laravel/framework/src/Illuminate/Database/Connection.php(478): Illuminate\\Database\\Connection->affectingStatement()
#5 /home/ploi/10ofthose.servers.tc/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(3218): Illuminate\\Database\\Connection->delete()
#6 /home/ploi/10ofthose.servers.tc/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(1076): Illuminate\\Database\\Query\\Builder->delete()
#7 /home/ploi/10ofthose.servers.tc/vendor/laravel/framework/src/Illuminate/Support/Traits/ForwardsCalls.php(23): Illuminate\\Database\\Eloquent\\Builder->delete()
#8 /home/ploi/10ofthose.servers.tc/vendor/laravel/framework/src/Illuminate/Support/Traits/ForwardsCalls.php(52): Illuminate\\Database\\Eloquent\\Relations\\Relation->forwardCallTo()
#9 /home/ploi/10ofthose.servers.tc/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Relations/Relation.php(481): Illuminate\\Database\\Eloquent\\Relations\\Relation->forwardDecoratedCallTo()
#10 /home/ploi/10ofthose.servers.tc/vendor/kalnoy/nestedset/src/NodeTrait.php(631): Illuminate\\Database\\Eloquent\\Relations\\Relation->__call()
#11 /home/ploi/10ofthose.servers.tc/vendor/kalnoy/nestedset/src/NodeTrait.php(56): GetCandy\\Models\\Collection->deleteDescendants()
#12 /home/ploi/10ofthose.servers.tc/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(404): GetCandy\\Models\\Collection::Kalnoy\\Nestedset\\{closure}()
#13 /home/ploi/10ofthose.servers.tc/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(249): Illuminate\\Events\\Dispatcher->Illuminate\\Events\\{closure}()
#14 /home/ploi/10ofthose.servers.tc/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasEvents.php(189): Illuminate\\Events\\Dispatcher->dispatch()
#15 /home/ploi/10ofthose.servers.tc/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1267): Illuminate\\Database\\Eloquent\\Model->fireModelEvent()
#16 /home/ploi/10ofthose.servers.tc/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1299): Illuminate\\Database\\Eloquent\\Model->delete()
#17 /home/ploi/10ofthose.servers.tc/vendor/getcandy/admin/src/Http/Livewire/Components/Collections/CollectionGroupShow.php(303): Illuminate\\Database\\Eloquent\\Model->forceDelete()
#18 /home/ploi/10ofthose.servers.tc/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): GetCandy\\Hub\\Http\\Livewire\\Components\\Collections\\CollectionGroupShow->deleteCollection()
#19 /home/ploi/10ofthose.servers.tc/vendor/laravel/framework/src/Illuminate/Container/Util.php(40): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#20 /home/ploi/10ofthose.servers.tc/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
#21 /home/ploi/10ofthose.servers.tc/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\\Container\\BoundMethod::callBoundMethod()
#22 /home/ploi/10ofthose.servers.tc/vendor/livewire/livewire/src/ComponentConcerns/HandlesActions.php(149): Illuminate\\Container\\BoundMethod::call()
#23 /home/ploi/10ofthose.servers.tc/vendor/livewire/livewire/src/HydrationMiddleware/PerformActionCalls.php(38): Livewire\\Component->callMethod()
#24 /home/ploi/10ofthose.servers.tc/vendor/livewire/livewire/src/LifecycleManager.php(89): Livewire\\HydrationMiddleware\\PerformActionCalls::hydrate()
#25 /home/ploi/10ofthose.servers.tc/vendor/livewire/livewire/src/Connection/ConnectionHandler.php(13): Livewire\\LifecycleManager->hydrate()
#26 /home/ploi/10ofthose.servers.tc/vendor/livewire/livewire/src/Controllers/HttpConnectionHandler.php(20): Livewire\\Connection\\ConnectionHandler->handle()
#27 /home/ploi/10ofthose.servers.tc/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(48): Livewire\\Controllers\\HttpConnectionHandler->__invoke()
#28 /home/ploi/10ofthose.servers.tc/vendor/laravel/framework/src/Illuminate/Routing/Route.php(262): Illuminate\\Routing\\ControllerDispatcher->dispatch()
#29 /home/ploi/10ofthose.servers.tc/vendor/laravel/framework/src/Illuminate/Routing/Route.php(205): Illuminate\\Routing\\Route->runController()
#30 /home/ploi/10ofthose.servers.tc/vendor/laravel/framework/src/Illuminate/Routing/Router.php(721): Illuminate\\Routing\\Route->run()
#31 /home/ploi/10ofthose.servers.tc/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}()
#32 /home/ploi/10ofthose.servers.tc/app/Http/Middleware/CheckAffiliate.php(44): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#33 /home/ploi/10ofthose.servers.tc/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): App\\Http\\Middleware\\CheckAffiliate->handle()
#34 /home/ploi/10ofthose.servers.tc/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(50): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#35 /home/ploi/10ofthose.servers.tc/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle()
#36 /home/ploi/10ofthose.servers.tc/vendor/laravel/framework/src/Illuminate/Auth/Middleware/Authenticate.php(44): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#37 /home/ploi/10ofthose.servers.tc/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Auth\\Middleware\\Authenticate->handle()
#38 /home/ploi/10ofthose.servers.tc/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(78): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#39 /home/ploi/10ofthose.servers.tc/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle()
#40 /home/ploi/10ofthose.servers.tc/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#41 /home/ploi/10ofthose.servers.tc/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle()
#42 /home/ploi/10ofthose.servers.tc/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(121): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#43 /home/ploi/10ofthose.servers.tc/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\\Session\\Middleware\\StartSession->handleStatefulRequest()
#44 /home/ploi/10ofthose.servers.tc/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Session\\Middleware\\StartSession->handle()
#45 /home/ploi/10ofthose.servers.tc/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#46 /home/ploi/10ofthose.servers.tc/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle()
#47 /home/ploi/10ofthose.servers.tc/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#48 /home/ploi/10ofthose.servers.tc/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle()
#49 /home/ploi/10ofthose.servers.tc/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#50 /home/ploi/10ofthose.servers.tc/vendor/laravel/framework/src/Illuminate/Routing/Router.php(723): Illuminate\\Pipeline\\Pipeline->then()
#51 /home/ploi/10ofthose.servers.tc/vendor/laravel/framework/src/Illuminate/Routing/Router.php(698): Illuminate\\Routing\\Router->runRouteWithinStack()
#52 /home/ploi/10ofthose.servers.tc/vendor/laravel/framework/src/Illuminate/Routing/Router.php(662): Illuminate\\Routing\\Router->runRoute()
#53 /home/ploi/10ofthose.servers.tc/vendor/laravel/framework/src/Illuminate/Routing/Router.php(651): Illuminate\\Routing\\Router->dispatchToRoute()
#54 /home/ploi/10ofthose.servers.tc/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(167): Illuminate\\Routing\\Router->dispatch()
#55 /home/ploi/10ofthose.servers.tc/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}()
#56 /home/ploi/10ofthose.servers.tc/vendor/statamic/cms/src/Http/Middleware/DisableFloc.php(18): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#57 /home/ploi/10ofthose.servers.tc/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Statamic\\Http\\Middleware\\DisableFloc->handle()
#58 /home/ploi/10ofthose.servers.tc/vendor/statamic/cms/src/Http/Middleware/CheckMultisite.php(14): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#59 /home/ploi/10ofthose.servers.tc/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Statamic\\Http\\Middleware\\CheckMultisite->handle()
#60 /home/ploi/10ofthose.servers.tc/vendor/statamic/cms/src/Http/Middleware/CheckComposerJsonScripts.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#61 /home/ploi/10ofthose.servers.tc/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Statamic\\Http\\Middleware\\CheckComposerJsonScripts->handle()
#62 /home/ploi/10ofthose.servers.tc/vendor/statamic/cms/src/Http/Middleware/PoweredByHeader.php(19): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#63 /home/ploi/10ofthose.servers.tc/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Statamic\\Http\\Middleware\\PoweredByHeader->handle()
#64 /home/ploi/10ofthose.servers.tc/vendor/livewire/livewire/src/DisableBrowserCache.php(19): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#65 /home/ploi/10ofthose.servers.tc/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Livewire\\DisableBrowserCache->handle()
#66 /home/ploi/10ofthose.servers.tc/vendor/barryvdh/laravel-debugbar/src/Middleware/InjectDebugbar.php(60): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#67 /home/ploi/10ofthose.servers.tc/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Barryvdh\\Debugbar\\Middleware\\InjectDebugbar->handle()
#68 /home/ploi/10ofthose.servers.tc/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#69 /home/ploi/10ofthose.servers.tc/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull->handle()
#70 /home/ploi/10ofthose.servers.tc/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(36): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#71 /home/ploi/10ofthose.servers.tc/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\TrimStrings->handle()
#72 /home/ploi/10ofthose.servers.tc/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#73 /home/ploi/10ofthose.servers.tc/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle()
#74 /home/ploi/10ofthose.servers.tc/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(86): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#75 /home/ploi/10ofthose.servers.tc/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle()
#76 /home/ploi/10ofthose.servers.tc/vendor/fruitcake/laravel-cors/src/HandleCors.php(38): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#77 /home/ploi/10ofthose.servers.tc/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fruitcake\\Cors\\HandleCors->handle()
#78 /home/ploi/10ofthose.servers.tc/vendor/laravel/framework/src/Illuminate/Http/Middleware/TrustProxies.php(39): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#79 /home/ploi/10ofthose.servers.tc/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Http\\Middleware\\TrustProxies->handle()
#80 /home/ploi/10ofthose.servers.tc/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#81 /home/ploi/10ofthose.servers.tc/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(142): Illuminate\\Pipeline\\Pipeline->then()
#82 /home/ploi/10ofthose.servers.tc/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(111): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
#83 /home/ploi/10ofthose.servers.tc/public/index.php(52): Illuminate\\Foundation\\Http\\Kernel->handle()
#84 {main}
```

Happy to provide more info if you can't recreate on your side.

**Comment by alecritson** [comment]
Thanks @ryanmitchell I've started a PR for this here https://github.com/getcandy/getcandy/pull/295 which should factor in descendant relationships, fix remove of URLs and wraps it in a transaction in case something goes wrong.
