### ISSUE TITLE
Error on the customers tab in admin

### ISSUE THREAD

**Issue by miekroel** [getcandy/getcandy#40]
When going to the customer tab i get an error on a wrong collumn name (wich makes sence as they are called first name and last name (not name)

System
- php 8.1.1
- mysql driver for search 

Steps to reproduce 
- create a fresh laravel app 
- install and configure getcandy
- create product (probably optional) 
- go to the customers tab 

![image](https://user-images.githubusercontent.com/26734275/148676443-074f9c23-bd6e-4b2b-b638-2f0d8d1db29e.png)

```stacktrace
[2022-01-09 09:12:45] local.ERROR: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'getcandy_customers.name' in 'where clause' (SQL: select count(*) as aggregate from `getcandy_customers` where (`getcandy_customers`.`id` LIKE %% OR `getcandy_customers`.`name` LIKE %% OR `getcandy_customers`.`company_name` LIKE %% OR `getcandy_customers`.`vat_no` LIKE %% OR `getcandy_customers`.`account_no` LIKE %%)) (View: /Users/brianverschoore/Sites/getCandy/vendor/getcandy/admin/resources/views/livewire/components/customers/index.blade.php) {"view":{"view":"/Users/brianverschoore/Sites/getCandy/vendor/laravel/framework/src/Illuminate/Database/Connection.php","data":[]},"userId":1,"exception":"[object] (Facade\\Ignition\\Exceptions\\ViewException(code: 0): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'getcandy_customers.name' in 'where clause' (SQL: select count(*) as aggregate from `getcandy_customers` where (`getcandy_customers`.`id` LIKE %% OR `getcandy_customers`.`name` LIKE %% OR `getcandy_customers`.`company_name` LIKE %% OR `getcandy_customers`.`vat_no` LIKE %% OR `getcandy_customers`.`account_no` LIKE %%)) (View: /Users/brianverschoore/Sites/getCandy/vendor/getcandy/admin/resources/views/livewire/components/customers/index.blade.php) at /Users/brianverschoore/Sites/getCandy/vendor/laravel/framework/src/Illuminate/Database/Connection.php:705)
[stacktrace]
#0 /Users/brianverschoore/Sites/getCandy/vendor/laravel/framework/src/Illuminate/Database/Connection.php(665): Illuminate\\Database\\Connection->runQueryCallback('select count(*)...', Array, Object(Closure))
#1 /Users/brianverschoore/Sites/getCandy/vendor/laravel/framework/src/Illuminate/Database/Connection.php(369): Illuminate\\Database\\Connection->run('select count(*)...', Array, Object(Closure))
#2 /Users/brianverschoore/Sites/getCandy/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2352): Illuminate\\Database\\Connection->select('select count(*)...', Array, true)
#3 /Users/brianverschoore/Sites/getCandy/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2340): Illuminate\\Database\\Query\\Builder->runSelect()
#4 /Users/brianverschoore/Sites/getCandy/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2874): Illuminate\\Database\\Query\\Builder->Illuminate\\Database\\Query\\{closure}()
#5 /Users/brianverschoore/Sites/getCandy/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2341): Illuminate\\Database\\Query\\Builder->onceWithColumns(Array, Object(Closure))
#6 /Users/brianverschoore/Sites/getCandy/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2801): Illuminate\\Database\\Query\\Builder->get(Array)
#7 /Users/brianverschoore/Sites/getCandy/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2729): Illuminate\\Database\\Query\\Builder->aggregate('count', Array)
#8 /Users/brianverschoore/Sites/getCandy/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(1655): Illuminate\\Database\\Query\\Builder->count()
#9 /Users/brianverschoore/Sites/getCandy/vendor/yab/laravel-scout-mysql-driver/src/Engines/MySQLEngine.php(80): Illuminate\\Database\\Eloquent\\Builder->__call('count', Array)
#10 /Users/brianverschoore/Sites/getCandy/vendor/yab/laravel-scout-mysql-driver/src/Engines/MySQLEngine.php(115): Yab\\MySQLScout\\Engines\\MySQLEngine->search(Object(Laravel\\Scout\\Builder))
#11 /Users/brianverschoore/Sites/getCandy/vendor/laravel/scout/src/Builder.php(373): Yab\\MySQLScout\\Engines\\MySQLEngine->paginate(Object(Laravel\\Scout\\Builder), 50, 1)
#12 /Users/brianverschoore/Sites/getCandy/vendor/getcandy/admin/src/Http/Livewire/Components/Customers/CustomersIndex.php(39): Laravel\\Scout\\Builder->paginate(50)
#13 /Users/brianverschoore/Sites/getCandy/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): GetCandy\\Hub\\Http\\Livewire\\Components\\Customers\\CustomersIndex->getCustomersProperty()
#14 /Users/brianverschoore/Sites/getCandy/vendor/laravel/framework/src/Illuminate/Container/Util.php(40): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#15 /Users/brianverschoore/Sites/getCandy/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure(Object(Closure))
#16 /Users/brianverschoore/Sites/getCandy/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#17 /Users/brianverschoore/Sites/getCandy/vendor/laravel/framework/src/Illuminate/Container/Container.php(653): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#18 /Users/brianverschoore/Sites/getCandy/vendor/livewire/livewire/src/Component.php(285): Illuminate\\Container\\Container->call(Array)
#19 /Users/brianverschoore/Sites/getCandy/vendor/getcandy/admin/src/../resources/views/livewire/components/customers/index.blade.php(113): Livewire\\Component->__get('customers')
#20 /Users/brianverschoore/Sites/getCandy/vendor/livewire/livewire/src/ComponentConcerns/RendersLivewireComponents.php(49): include('/Users/brianver...')
#21 /Users/brianverschoore/Sites/getCandy/vendor/livewire/livewire/src/ComponentConcerns/RendersLivewireComponents.php(50): GetCandy\\Hub\\Http\\Livewire\\Components\\Customers\\CustomersIndex->Livewire\\ComponentConcerns\\{closure}()
#22 /Users/brianverschoore/Sites/getCandy/vendor/laravel/framework/src/Illuminate/View/Engines/CompilerEngine.php(61): Livewire\\CompilerEngineForIgnition->evaluatePath('/Users/brianver...', Array)
#23 /Users/brianverschoore/Sites/getCandy/vendor/facade/ignition/src/Views/Engines/CompilerEngine.php(37): Illuminate\\View\\Engines\\CompilerEngine->get('/Users/brianver...', Array)
#24 /Users/brianverschoore/Sites/getCandy/vendor/laravel/framework/src/Illuminate/View/View.php(139): Facade\\Ignition\\Views\\Engines\\CompilerEngine->get('/Users/brianver...', Array)
#25 /Users/brianverschoore/Sites/getCandy/vendor/laravel/framework/src/Illuminate/View/View.php(122): Illuminate\\View\\View->getContents()
#26 /Users/brianverschoore/Sites/getCandy/vendor/laravel/framework/src/Illuminate/View/View.php(91): Illuminate\\View\\View->renderContents()
#27 /Users/brianverschoore/Sites/getCandy/vendor/livewire/livewire/src/Component.php(233): Illuminate\\View\\View->render()
#28 /Users/brianverschoore/Sites/getCandy/vendor/livewire/livewire/src/HydrationMiddleware/RenderView.php(14): Livewire\\Component->output()
#29 /Users/brianverschoore/Sites/getCandy/vendor/livewire/livewire/src/LifecycleManager.php(141): Livewire\\HydrationMiddleware\\RenderView::dehydrate(Object(GetCandy\\Hub\\Http\\Livewire\\Components\\Customers\\CustomersIndex), Object(Livewire\\Response))
#30 /Users/brianverschoore/Sites/getCandy/vendor/livewire/livewire/src/LivewireManager.php(106): Livewire\\LifecycleManager->initialDehydrate()
#31 /Users/brianverschoore/Sites/getCandy/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(261): Livewire\\LivewireManager->mount('hub.components....')
#32 /Users/brianverschoore/Sites/getCandy/vendor/getcandy/admin/src/../resources/views/livewire/pages/customers/index.blade.php(11): Illuminate\\Support\\Facades\\Facade::__callStatic('mount', Array)
#33 /Users/brianverschoore/Sites/getCandy/vendor/livewire/livewire/src/ComponentConcerns/RendersLivewireComponents.php(49): include('/Users/brianver...')
#34 /Users/brianverschoore/Sites/getCandy/vendor/livewire/livewire/src/ComponentConcerns/RendersLivewireComponents.php(50): GetCandy\\Hub\\Http\\Livewire\\Pages\\Customers\\CustomersIndex->Livewire\\ComponentConcerns\\{closure}()
#35 /Users/brianverschoore/Sites/getCandy/vendor/laravel/framework/src/Illuminate/View/Engines/CompilerEngine.php(61): Livewire\\CompilerEngineForIgnition->evaluatePath('/Users/brianver...', Array)
#36 /Users/brianverschoore/Sites/getCandy/vendor/facade/ignition/src/Views/Engines/CompilerEngine.php(37): Illuminate\\View\\Engines\\CompilerEngine->get('/Users/brianver...', Array)
#37 /Users/brianverschoore/Sites/getCandy/vendor/laravel/framework/src/Illuminate/View/View.php(139): Facade\\Ignition\\Views\\Engines\\CompilerEngine->get('/Users/brianver...', Array)
#38 /Users/brianverschoore/Sites/getCandy/vendor/laravel/framework/src/Illuminate/View/View.php(122): Illuminate\\View\\View->getContents()
#39 /Users/brianverschoore/Sites/getCandy/vendor/laravel/framework/src/Illuminate/View/View.php(91): Illuminate\\View\\View->renderContents()
#40 /Users/brianverschoore/Sites/getCandy/vendor/livewire/livewire/src/Component.php(233): Illuminate\\View\\View->render()
#41 /Users/brianverschoore/Sites/getCandy/vendor/livewire/livewire/src/HydrationMiddleware/RenderView.php(14): Livewire\\Component->output()
#42 /Users/brianverschoore/Sites/getCandy/vendor/livewire/livewire/src/LifecycleManager.php(141): Livewire\\HydrationMiddleware\\RenderView::dehydrate(Object(GetCandy\\Hub\\Http\\Livewire\\Pages\\Customers\\CustomersIndex), Object(Livewire\\Response))
#43 /Users/brianverschoore/Sites/getCandy/vendor/livewire/livewire/src/Macros/livewire-view-component.blade.php(3): Livewire\\LifecycleManager->initialDehydrate()
#44 /Users/brianverschoore/Sites/getCandy/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php(107): require('/Users/brianver...')
#45 /Users/brianverschoore/Sites/getCandy/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php(108): Illuminate\\Filesystem\\Filesystem::Illuminate\\Filesystem\\{closure}()
#46 /Users/brianverschoore/Sites/getCandy/vendor/laravel/framework/src/Illuminate/View/Engines/PhpEngine.php(58): Illuminate\\Filesystem\\Filesystem->getRequire('/Users/brianver...', Array)
#47 /Users/brianverschoore/Sites/getCandy/vendor/livewire/livewire/src/ComponentConcerns/RendersLivewireComponents.php(35): Illuminate\\View\\Engines\\PhpEngine->evaluatePath('/Users/brianver...', Array)
#48 /Users/brianverschoore/Sites/getCandy/vendor/laravel/framework/src/Illuminate/View/Engines/CompilerEngine.php(61): Livewire\\CompilerEngineForIgnition->evaluatePath('/Users/brianver...', Array)
#49 /Users/brianverschoore/Sites/getCandy/vendor/facade/ignition/src/Views/Engines/CompilerEngine.php(37): Illuminate\\View\\Engines\\CompilerEngine->get('/Users/brianver...', Array)
#50 /Users/brianverschoore/Sites/getCandy/vendor/laravel/framework/src/Illuminate/View/View.php(139): Facade\\Ignition\\Views\\Engines\\CompilerEngine->get('/Users/brianver...', Array)
#51 /Users/brianverschoore/Sites/getCandy/vendor/laravel/framework/src/Illuminate/View/View.php(122): Illuminate\\View\\View->getContents()
#52 /Users/brianverschoore/Sites/getCandy/vendor/laravel/framework/src/Illuminate/View/View.php(91): Illuminate\\View\\View->renderContents()
#53 /Users/brianverschoore/Sites/getCandy/vendor/laravel/framework/src/Illuminate/Http/Response.php(69): Illuminate\\View\\View->render()
#54 /Users/brianverschoore/Sites/getCandy/vendor/laravel/framework/src/Illuminate/Http/Response.php(35): Illuminate\\Http\\Response->setContent(Object(Illuminate\\View\\View))
#55 /Users/brianverschoore/Sites/getCandy/vendor/laravel/framework/src/Illuminate/Routing/Router.php(794): Illuminate\\Http\\Response->__construct(Object(Illuminate\\View\\View), 200, Array)
#56 /Users/brianverschoore/Sites/getCandy/vendor/laravel/framework/src/Illuminate/Routing/Router.php(763): Illuminate\\Routing\\Router::toResponse(Object(Illuminate\\Http\\Request), Object(Illuminate\\View\\View))
#57 /Users/brianverschoore/Sites/getCandy/vendor/laravel/framework/src/Illuminate/Routing/Router.php(695): Illuminate\\Routing\\Router->prepareResponse(Object(Illuminate\\Http\\Request), Object(Illuminate\\View\\View))
#58 /Users/brianverschoore/Sites/getCandy/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#59 /Users/brianverschoore/Sites/getCandy/vendor/laravel/framework/src/Illuminate/Auth/Middleware/Authorize.php(45): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#60 /Users/brianverschoore/Sites/getCandy/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Auth\\Middleware\\Authorize->handle(Object(Illuminate\\Http\\Request), Object(Closure), 'catalogue:manag...')
#61 /Users/brianverschoore/Sites/getCandy/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(50): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#62 /Users/brianverschoore/Sites/getCandy/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#63 /Users/brianverschoore/Sites/getCandy/vendor/laravel/framework/src/Illuminate/Auth/Middleware/Authenticate.php(44): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#64 /Users/brianverschoore/Sites/getCandy/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Auth\\Middleware\\Authenticate->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#65 /Users/brianverschoore/Sites/getCandy/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(78): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#66 /Users/brianverschoore/Sites/getCandy/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#67 /Users/brianverschoore/Sites/getCandy/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#68 /Users/brianverschoore/Sites/getCandy/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#69 /Users/brianverschoore/Sites/getCandy/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(121): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#70 /Users/brianverschoore/Sites/getCandy/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\\Session\\Middleware\\StartSession->handleStatefulRequest(Object(Illuminate\\Http\\Request), Object(Illuminate\\Session\\Store), Object(Closure))
#71 /Users/brianverschoore/Sites/getCandy/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Session\\Middleware\\StartSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#72 /Users/brianverschoore/Sites/getCandy/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#73 /Users/brianverschoore/Sites/getCandy/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#74 /Users/brianverschoore/Sites/getCandy/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#75 /Users/brianverschoore/Sites/getCandy/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#76 /Users/brianverschoore/Sites/getCandy/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#77 /Users/brianverschoore/Sites/getCandy/vendor/laravel/framework/src/Illuminate/Routing/Router.php(697): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#78 /Users/brianverschoore/Sites/getCandy/vendor/laravel/framework/src/Illuminate/Routing/Router.php(672): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
#79 /Users/brianverschoore/Sites/getCandy/vendor/laravel/framework/src/Illuminate/Routing/Router.php(636): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
#80 /Users/brianverschoore/Sites/getCandy/vendor/laravel/framework/src/Illuminate/Routing/Router.php(625): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
#81 /Users/brianverschoore/Sites/getCandy/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(167): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
#82 /Users/brianverschoore/Sites/getCandy/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
#83 /Users/brianverschoore/Sites/getCandy/vendor/livewire/livewire/src/DisableBrowserCache.php(19): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#84 /Users/brianverschoore/Sites/getCandy/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Livewire\\DisableBrowserCache->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#85 /Users/brianverschoore/Sites/getCandy/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#86 /Users/brianverschoore/Sites/getCandy/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#87 /Users/brianverschoore/Sites/getCandy/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#88 /Users/brianverschoore/Sites/getCandy/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#89 /Users/brianverschoore/Sites/getCandy/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(40): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#90 /Users/brianverschoore/Sites/getCandy/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\TrimStrings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#91 /Users/brianverschoore/Sites/getCandy/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#92 /Users/brianverschoore/Sites/getCandy/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#93 /Users/brianverschoore/Sites/getCandy/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(86): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#94 /Users/brianverschoore/Sites/getCandy/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#95 /Users/brianverschoore/Sites/getCandy/vendor/fruitcake/laravel-cors/src/HandleCors.php(38): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#96 /Users/brianverschoore/Sites/getCandy/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fruitcake\\Cors\\HandleCors->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#97 /Users/brianverschoore/Sites/getCandy/vendor/laravel/framework/src/Illuminate/Http/Middleware/TrustProxies.php(39): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#98 /Users/brianverschoore/Sites/getCandy/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Http\\Middleware\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#99 /Users/brianverschoore/Sites/getCandy/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#100 /Users/brianverschoore/Sites/getCandy/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(142): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#101 /Users/brianverschoore/Sites/getCandy/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(111): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#102 /Users/brianverschoore/Sites/getCandy/public/index.php(52): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#103 /Users/brianverschoore/.composer/vendor/laravel/valet/server.php(234): require('/Users/brianver...')
#104 {main}
```

**Comment by briavers** [comment]
used my wrong account to post it 🙄

**Comment by RhysLees** [comment]
Also have the same problem.

**Comment by alecritson** [comment]
Thanks for reporting, we have a fix ready to be added to the next release :)
